#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 17 12:04:47 2022

@author: neerbos
"""
import uclchem
import pandas as pd
import matplotlib.pyplot as plt
import time as tm
import numpy as np
import smtplib as sp
from multiprocessing import Pool
import itertools

pc,year=30.9E12,3.15e7 #in km, s
outSpecies="SO CO"
density,vs=1e3,30
alldensity=[1e3,1e4,1e5,1e6]
allv=[10,15,20,25,30,35,40,45,50,55,60]
allcrir,allvisex=[0.1,1,10,100],[1,2,5,10] #crir=cosmic ray ion rate, visex=visual extinction
alluv=[0.1,1,10,100] #in Habing
param_dict = {"phase": 1, "switch": 0, "collapse": 1, "writeStep": 1,
				   "outSpecies": outSpecies, "initialDens": 1e2, "initialTemp":10.0,
				   "maxTemp":1e5, "finalTime":6.0e6, "radfield" : 1.0,
				   "zeta" : 1.0, "rout" : 0.05, "baseAv" : 1.0,
				   "outputFile":"../output/collapse_outputs/{}.dat".format(density),
				   "abundSaveFile":"../output/collapse_outputs/start{}.dat".format(density)}
def collapse():
	for density in alldensity:            

		param_dict["finalDens"]=density	#change for specific model no; 1e3,4,5 or 6
		param_dict["vs"]=vs		#similar, shock speed in km/s
		param_dict["outputFile"]="../output/collapse_outputs/{}.dat".format(density)
		param_dict["abundSaveFile"]="../output/collapse_outputs/start{}.dat".format(density)
		uclchem.run_model(param_dict)
	phase1_df=uclchem.read_output_file("../output/collapse_outputs/{}.dat".format(density))
#species=["CO","#CO","HCN","#HCN"]
#param_dict.pop("abundSaveFile") #this is still set to startcollapse.dat from phase 1 so remove it or change it.
collapse()