#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Mar  4 10:56:33 2022

@author: neerbos
"""
import uclchem
import pandas as pd
import matplotlib.pyplot as plt
#set a parameter dictionary for phase 1 collapse model

outSpecies="SO CO"
""" param_dict = {"phase": 1, "switch": 1, "collapse": 1, "writeStep": 1,
               "outSpecies": outSpecies, "initialDens": 1e2, "initialTemp":10.0,
               "finalDens":1e5, "finalTime":5.0e6,
               "outputFile":"../examples/test-output/phase1-full.dat",
               "abundSaveFile":"../examples/test-output/startcollapse.dat"}"""
param_dict = {"phase": 1, "switch": 1, "collapse": 0, "writeStep": 1,
               "outSpecies": outSpecies, "initialDens": 1e2, "initialTemp":10.0,
               "maxTemp":1e5, "finalTime":6.0e6, "radfield" : 1.0,
               "zeta" : 1.0, "rout" : 0.05, "baseAv" : 1.5,
               "outputFile":"../examples/test-output/phase1-full.dat",
               "abundSaveFile":"../examples/test-output/startcollapse.dat"}
param_dict["finalDens"]=1e5		#change for specific model no; 1e3,4,5 or 6
param_dict["vs"]=40				#similar, shock speed in km/s
"""uclchem.run_model(param_dict)
phase1_df=uclchem.read_output_file("../examples/test-output/phase1-full.dat")
species=["CO","#CO","HCN","#HCN"]
fig,ax=uclchem.create_abundance_plot(phase1_df,species)
ax=ax.set(xscale="log")
#plt.show()"""
#read old abundances and do cshock behaviour
param_dict["phase"]=2

#change other bits of input to set up phase 2
param_dict["initialDens"]=1e5
param_dict["tempindx"]=3 #selects mass of protostar (see cloud.f90)
param_dict["finalTime"]=1e6
param_dict["switch"]=0

param_dict.pop("abundSaveFile") #this is still set to startcollapse.dat from phase 1 so remove it or change it.
param_dict["abundLoadFile"]="../examples/test-output/startcollapse.dat"
param_dict["outputFile"]="../examples/test-output/phase2-full.dat"


uclchem.run_model(param_dict)
phase2_df=uclchem.read_output_file("../examples/test-output/phase2-full.dat")
species=["CO","H2O","CH3OH","#CO","#H2O","#CH3OH"]

fig,[ax,ax2]=plt.subplots(1,2,figsize=(16,9))
ax=uclchem.plot_species(ax,phase2_df,species)
settings=ax.set(yscale="log",xlim=(1,1e6),ylim=(1e-10,1e-2),
            xlabel="Time / years", 
            ylabel="Fractional Abundance",xscale="log")

ax2.plot(phase2_df["Time"],phase2_df["Density"],color="black")
ax3=ax2.twinx()
ax3.plot(phase2_df["Time"],phase2_df["gasTemp"],color="red")
ax2.set(xlabel="Time / year",ylabel="Density")
ax3.set(ylabel="Temperature",facecolor="red",xlim=(1,1e7),xscale="log")
ax3.tick_params(axis='y', colors='red')
plt.show()
