#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 25 13:06:58 2022

@author: neerbos
"""
import uclchem
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn
from scipy import integrate
from tabulate import tabulate as tbl
from collections import defaultdict

jon=True
#set a parameter dictionary for phase 1 collapse model
pc,year=30.9E12,3.15e7 #in km, s
dens,vel=1E5,40
alldensity=[1e3,1e4,1e5,1e6]
allv=[5,10,15,20,25,30,35,40,45,50,55,60]
allcrir,alluv=[0.1,1,10,100],[0.1,1,10,100] #crir=cosmic ray ion rate uv in Habing
notspecies=["Time","Density","gasTemp","av","zeta","point","BULK","SURFACE","radfield"]
jonlist=["H2O","HCL","C3H2","CS","HS","H2CN","HCN","H2CS","CH3OH","NH3","NS","H2S","CH","CN","HCO","O2","OH","OCS","HNO","HNC","CO2","SO"]
elementList = [
    "H",
    "D",
    "HE",
    "C",
    "N",
    "O",
    "F",
    "P",
    "S",
    "CL",
    "LI",
    "NA",
    "MG",
    "SI",
    "PAH",
    "15N",
    "13C",
    "18O",
    "SURFACE",
    "BULK",
    "Time",
]
vel,dens=10,1e4
output_file="../output/shocks_output/Cshock{}-{}-1-1.dat".format(dens,vel)
df=uclchem.analysis.read_output_file(output_file=output_file)

def enhanced(df,dens,vel,printit=False):
    enhs,dests,maxs,starts={},{},{},{} #lists of enhancement factors, destruction and max abundances respectively
    disstime=uclchem.utils.cshock_dissipation_time(vel, dens)
    idx1,idx2=df["Time"].sub(disstime).abs().idxmin(),df["Time"].sub(10*disstime).abs().idxmin() #finds index of time closest to dissipation time
    for column in df:
        if jon:
            if column in jonlist:
                avg1=integrate.trapz(df[column][0:idx1],x=df["Time"][0:idx1])/df["Time"][idx1]
                #average abundance throughout the shock
                avg2=integrate.trapz(df[column][idx1:idx2],x=df["Time"][idx1:idx2])/(df["Time"][idx2]-df["Time"][idx1])
                #average abundance after the shock
                start=df[column][0]
                change=avg1**2/start
                destroy=avg1**2/avg2
                #if change >=1:
                enhs[column]=change
                dests[column]=destroy
                maxs[column]=max(df[column])
                starts[column]=start
        elif column not in notspecies and column not in elementList:
            if not "@" in column and not "#" in column and not "+" in column:
                avg1=integrate.trapz(df[column][0:idx1],x=df["Time"][0:idx1])/df["Time"][idx1]
                #average abundance throughout the shock
                avg2=integrate.trapz(df[column][idx1:idx2],x=df["Time"][idx1:idx2])/(df["Time"][idx2]-df["Time"][idx1])
                #average abundance after the shock
                start=df[column][0]
                change=avg1/start
                destroy=avg1/avg2
                #if change >=1:
                enhs[column]=change
                dests[column]=destroy
                maxs[column]=max(df[column])
                starts[column]=start
    if printit:      
        print("enhanced:",enhs,"\n","destroyed:",dests,"\n","maxima:",maxs)       
    return enhs,dests,maxs,starts


def table(shock="C",minenh=1E3,mindest=100,minabd=1E-9,writefile=False):
    """ gives enhanced species in blue and destroyed species in red
    minenh, mindest and minabd give the minimum values of the enhancement factors, destruction factors and abundances
    to consider
    returns a nested dictionary of format eg {'1000.0-10':{'blue':list, 'red':list}}"""
    allshocks=defaultdict(dict)
    count=0
    if writefile:
        f=open("../output/speciestables/{}shock-jon{}.tex".format(shock,jon),"w")
        r"""\usepackage{tabularx}
        \usepackage{ltablex}
        \usepackage{seqsplit}
        \usepackage[margin=1cm]{geometry} % Changing page margin
        \usepackage{array}
        \usepackage{color}
        \usepackage{collcell}"""
        f.write("\\begin{tabularx}{500pt}{|s|s|s|s|s|} \n     vel\\textbackslash dens &1E3&1E4&1E5&1E6\\\\ \n\\hline \n")
    for vel in allv:
        if writefile:
            f.write("{}".format(vel))
        for dens in alldensity:

            output_file="../output/shocks_output/{}shock{}-{}-1-1.dat".format(shock,dens,vel)
            df=uclchem.analysis.read_output_file(output_file=output_file)
            enhs,dests,maxs,starts=enhanced(df,dens,vel)
            blue,red,black=[],[],[]
            for species in maxs:
                if maxs[species] >= minabd and starts[species]>=1E-12: #the species that start at minimum observable
                    if enhs[species]>=minenh:
                        blue.append(species)
                        count+=1
                    if dests[species]>=mindest:
                        red.append(species)
                        count+=1
                elif maxs[species] >= minabd:
                    black.append(species) #species enhanced from invisible to visible
                    count+=1
            allshocks["{}-{}".format(dens,vel)]["blue"]=blue
            allshocks["{}-{}".format(dens,vel)]["red"]=red
            allshocks["{}-{}".format(dens,vel)]["black"]=black
            if writefile:
                f.write("&\\textcolor{{blue}}{{{0}}}\\textcolor{{red}}{{{1}}}{2}".format(blue,red,black))#prints it in latex readable format
        if writefile:
            f.write("\\\\ \n\\hline \n")
    if writefile:
        f.write("\\end{tabularx}")
        f.close()
    print(count)
    return allshocks


def onelist(dens,vel,name="C"):
    output_file="../output/shocks_output/{}shock{}-{}-1-1.dat".format(name,dens,vel)
    df=uclchem.analysis.read_output_file(output_file=output_file)
    enhanced(df,dens,vel,printit=True)
def fulloutput():
    species=table()
    for i in species:
        print(i,species[i]["blue"])
onelist(1E5,30,name="C")
table=table(shock="C",writefile=False)
#print(table)
